### ISSUE TITLE
Ensure entity-date table is cleaned up

### ISSUE THREAD

**Issue by thcrock** [dssg/architect#24]
We drop tmp_entity_date tables when we're done with them, but if there's an error the drops won't run so they can pile up over time. In Architect#build_matrix, the entirety of the table's existence should be in a try block so we can drop the table in a finally block.

Original: https://github.com/dssg/timechop/issues/51

Also: https://github.com/dssg/timechop/issues/60

So really, we can either use a temporary table or the finally block.

**Comment by jesteria** [comment]
This issue was moved to dssg/triage#271
