### ISSUE TITLE
FeatureGroupCreator 'prefix' doesn't work if the prefix has underscores

### ISSUE THREAD

**Issue by thcrock** [dssg/architect#36]
The prefix_subsetter (https://github.com/dssg/architect/blob/master/architect/feature_group_creator.py#L9)

evaluates the prefix of a feature by splitting the feature name on underscore and taking the first result. This breaks when we're presented with prefixes that contain underscores.

This code should probably use the string builtin `.startswith`.

**Comment by nanounanue** [comment]
Confirmed, The current version doesn't support `prefix` with `_` like : `   prefix: 'traffic_stops'`
